### PR TITLE
Code Review: The Next Web Clone

### PR DESCRIPTION
**Pull request by martin-cervantes**
## Building with Responsive Design
* We put emphasis on how it behaves differently depending on the size of the screen
* We validate our HTML and CSS code
* We apply media queries with 2 different breakpoints

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, you did a great job building this project 👍 congratulations 😄 , the README file looks professional. However, in order to proceed we will have to fix the comments below, kindly check and fix the comments:
- ```In 768px``` 
```Currently```
cv
```Original```
cv1
```Currently```
cv3
```Original```
cv2
```Mobile screen size```
```Currently```
cv5
```Original```
cv4


Kindly make these changes and submit another code review 😄 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Comment by martin-cervantes1** [comment]
* we changed the way the "latest funding rounds" heading was displayed
 * remove round on mid-size as the original page

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS @mcervantes71 and @gabrie-lhilarion  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request merged**
